# Generated by Django 5.0.3 on 2024-03-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('co_author', models.CharField(max_length=30)),
                ('date_register', models.DateField()),
                ('borrowed', models.BooleanField(default=False)),
                ('borrowed_name', models.CharField(max_length=30)),
                ('loan_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('duration_time', models.TimeField()),
            ],
        ),
    ]
