# Generated by Django 5.0.3 on 2024-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_borrowed_name_alter_books_co_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_register',
            field=models.DateField(auto_now=True),
        ),
    ]
