# Generated by Django 5.0.3 on 2024-03-26 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_register',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
