# Generated by Django 5.0.3 on 2024-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_books_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrowed_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='co_author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='duration_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='loan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
