# Generated by Django 5.0.3 on 2024-03-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_alter_category_description"),
        ("users", "0002_alter_users_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="userId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.users",
            ),
            preserve_default=False,
        ),
    ]
