# Generated by Django 5.0.3 on 2024-03-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_rename_categoryid_books_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='borrowed_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='duration_time',
        ),
        migrations.RemoveField(
            model_name='books',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='return_date',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_name', models.CharField(blank=True, max_length=30, null=True)),
                ('loan_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('duration_time', models.TimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.books')),
            ],
        ),
    ]
