# Generated by Django 5.0.3 on 2024-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_books_borrowed_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='duration_time',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
